### ISSUE TITLE
Fix requirements.txt

### ISSUE THREAD

**Issue by iVishalr** [ArvindAROO/typeToHandwriting#2]
Rename `requiremts.txt` to `requirements.txt`.
 In `requirements.txt` write the following code

`pillow==6.2.0`.

 The user can install all the required libraries by typing `pip install -r requirements.txt`
 Specify Python Version in your `README.md`.

 Rename `imagesFiles` to `images`

 In `typeToHandwritten.py`, 

 Update :

 line 10 to `BG = Image.open("images/bg.png")`
 line 27 to `cases = Image.open("images/%s.png"%char)`

 Replace 
 ```
 if __name__ == '__main__':
     try:
         fileName = input("Enter file name: ")
         with open(fileName, 'r') as File:
             text = File.readlines()
             for line in text:
                 dataHandling(line)
             File.close()
         BG.save('new.bmp')
     except Exception as E:
         print(E)
 ```
 With
 ```
 if __name__ == '__main__':
     try:
         fileName = input("Enter file name: ")
         with open(fileName, 'r') as File:
             text = File.readlines()
             for line in text:
                 dataHandling(line)
             File.close()
         if(".txt" in fileName):
             BG.save(fileName[:-4]+'.bmp')
         else:
             BG.save(fileName+'.bmp')
     except Exception as E:
         print(E)
 ```
 Its better to save the output in the name of the input file.

**Comment by ArvindAROO** [comment]
Thanks for the generating this issue, all of them have been cleared
